s4u/pgpverify-maven-plugin

src/it/sigOkTestJar/pom.xml
src/it/sigOkTestJar/postbuild.bsh
src/main/java/com/github/s4u/plugins/AscArtifactHandler.java
src/main/java/com/github/s4u/plugins/PGPVerifyMojo.java

Previous approach blindly appended ".asc" to the classifier, breaking resolution for special artifacts like test JARs. Maven resolves these artifacts to a packaging type and file extension of "jar", but wasn't doing this here because the classifiers didn't match (since it had ".asc" at the end).
New approach provides the original classifier to Maven for it to apply standard look-up rules, then uses a new AscArtifactHandler that decorates the ArtifactHandler Maven returns for the artifact so that we fetch an artifact ending in ".asc".
Closes #22.

Stop kludging file extension into classifier

---

src/it/reactorProcess/invoker.properties
src/it/reactorProcess/pom.xml
src/it/reactorProcess/projectA/pom.xml
src/it/reactorProcess/projectB/pom.xml
src/it/reactorSkip/pom.xml
src/it/reactorSkip/projectA/pom.xml
src/it/reactorSkip/projectB/pom.xml
src/it/resources/local-repo/org/apache/maven/maven-parent/32-SNAPSHOT/maven-metadata.xml
src/it/resources/local-repo/org/apache/maven/maven-parent/32-SNAPSHOT/maven-parent-32-20180205.064755-1.pom
src/it/resources/local-repo/org/apache/maven/maven-parent/maven-metadata.xml
src/it/snapshotProcess/pom.xml
src/it/snapshotSkip/pom.xml
src/main/java/com/github/s4u/plugins/skipfilters/ProvidedDependencySkipper.java
src/main/java/com/github/s4u/plugins/skipfilters/ReactorDependencySkipper.java
src/main/java/com/github/s4u/plugins/skipfilters/SkipFilter.java
src/main/java/com/github/s4u/plugins/skipfilters/SnapshotDependencySkipper.java
src/main/java/com/github/s4u/plugins/skipfilters/SystemDependencySkipper.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

This adjusts PGP Verify to no longer complain about dependencies that are being built as part of the current multi-module build, in the event that the current build is not being signed. This allows `mvn clean install` to work properly without requiring that every build be signed, as long as the dependencies of all of the projects in the current build (minus the projects currently being built) are signed. 
The option can be toggled on or off with the new `verifyReactorDependencies` setting on the plug-in, in the event that projects want to require signing for both dependencies AND projects in the current reactor build.
Closes #29.

Ignore signatures on reactor dependencies by default

---

src/it/skipAll/pom.xml
src/it/skipAllByProp/pom.xml
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

Adding:
<configuration>
<skip>true</skip>
</configuration>
or running `mvn` with `-Dpgpverify.skip=true` property skips execution altogether.
Fixes #37

Added configuration to skip execution

---

src/it/quiet/pom.xml
src/it/quietByProp/pom.xml
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

The new "quiet" flag helps reducing noise in the output of successful builds by logging successful signature verifications on debug instead of info level.

Add "quiet" flag to reduce noise on successful builds

---

src/main/java/org/simplify4u/plugins/ArtifactInfo.java
src/main/java/org/simplify4u/plugins/KeyInfo.java
src/main/java/org/simplify4u/plugins/KeysMap.java
src/main/java/org/simplify4u/plugins/PGPSignatures.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/test/java/org/simplify4u/plugins/KeyInfoTest.java
src/test/java/org/simplify4u/plugins/KeysMapTest.java
src/test/resources/keysMap3.list

Added maven configuration parameter `strictNoSignature` to express missing signatures for individual artifacts akin to how public keys are specified, in the keys map.
The following use cases are covered:
- This provides support for issue #16:
- Ability to detect new artifacts that are missing signatures in set-up where there exist already some artifacts that are missing a signature. (Use case where `failNoSignature` is too strict.)
- Ability to make explicit for which artifacts we do not expect signatures.
Features:
- `quiet` parameter is respected.
- logs correct verification if artifact is missing signature consistent with keys map.

Add parameter 'strictNoSignature' to make missing signatures explicit in keys map

---

src/main/java/org/simplify4u/plugins/PGPKeysCache.java

In Fedora Toolbox-environment, key retrieval would fail due to a failure to move the downloaded public key from the temporary location to the PGP keys cache. By using the utility [Files.move](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#move(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.CopyOption...)) this action becomes more reliable and is guaranteed to be platform-independent.
The produced stack traces were not helpful in case of failure using the old move mechanism.
```java
java.io.IOException: Can't move file /tmp/-64362105801389810586520046351922325613pgp-public-key to /var/home/danny/dev/pgpverify-maven-plugin/target/it-repo/pgpkeys-cache/A6/AD/A6ADFC93EF34893E.asc
at org.simplify4u.plugins.PGPKeysCache.receiveKey (PGPKeysCache.java:135)
[...]
```

Fix unreliable move of freshly downloaded public key file

---

src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

Clarify the error message sufficiently such that the error message itself is sufficient to start investigating the problem.

Clarify error message for failure to process artifact signature

---

src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

The original formatting would leave an empty line after each `error` log entry.
I would expect that is accidental, so this patch removes it.

Remove excessive newline for error log entry.

---

src/it/sigOkKeysMapWithPlugins/keysmap.list
src/it/sigOkKeysMapWithPlugins/pom.xml
src/it/sigOkKeysMapWithPlugins/postbuild.groovy
src/main/java/org/simplify4u/plugins/ArtifactResolver.java

Add dependencies of build plug-ins as well as the build plug-ins themselves to the artifact validation list. (#54)
Given an earlier discovery that maven does not accept _Version Range_ specification for build plug-in dependencies, it is trivial to add plug-in dependency artifacts: there is no need for version conflict resolution.
@slawekjaranowski let me know if you really want to add this under another _configuration switch_. Right now this would be included as soon as build plug-ins are included. (Personally, I would like to avoid it.)

Add all build plug-in dependencies to the artifacts list whenever build plugins are validated

---

src/it/sigOkKeysMapWithPlugins/keysmap.list
src/it/sigOkKeysMapWithPlugins/pom.xml
src/it/sigOkKeysMapWithPlugins/postbuild.groovy
src/main/java/org/simplify4u/plugins/ArtifactResolver.java
src/main/java/org/simplify4u/plugins/MavenCompilerUtils.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java
src/test/java/org/simplify4u/plugins/MavenCompilerUtilsTest.java

This PR adds support for validating the annotation processors that might be listed in the maven-compiler-plugin configuration. These annotation processors are basically dependencies, but referenced through the configuration, instead of dependency listing.
- adds configuration parameter `verifyAtypical`, which currently only checks `maven-compiler-plugin` configuration for annotation processors, but can in the future contain other "exotic" locations.
- Fixes issue with dependencies filter being used for build plug-ins: filtering by scope is dangerous for plugins as these are all `runtime` artifacts.
- Created `Configuration` container such that all behavioral properties of the `ArtifactResolver` are combined in a single parameter.
- includes unit tests and IT tests
NOTE: As with build …

Validate annotation processors in maven-compiler-plugin

---

src/it/sigOkKeysMapWithPlugins/keysmap.list
src/it/sigOkKeysMapWithPlugins/pom.xml
src/it/sigOkKeysMapWithPlugins/postbuild.groovy
src/main/java/org/simplify4u/plugins/ArtifactResolver.java

This allows us to include reporting plug-ins in the artifact validation process.
Note: unless you want to introduce (yet another) configuration flag, this will be included in the `verifyPlugins` configuration parameter.
The `getReportPlugins()` method is marked deprecated, but even `maven-dependency-plugin` still uses it. I have not found another way to include the reporting plug-ins, so it seems reasonable to use this method for now. No replacement is indicated.

Add reporting plugins to artifact validation list when 'verifyPlugins'

---

src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/main/java/org/simplify4u/plugins/keysmap/KeysMap.java
src/test/java/org/simplify4u/plugins/keysmap/KeysMapTest.java

Emit a warning explaining the limitation of validation when a reference of trust is missing.
This should help to inform users of the limitations that exist when using this plugin if no source of trust is specified.
Please, feel free to suggest a better warning message. This message is a bit verbose.

Emit warning for missing keysmap.

---

src/main/java/org/simplify4u/plugins/keysmap/KeysMap.java

I don't like writing unit tests to satisfy coverage criteria, so I'll just simplify the control flow instead.

KeysMap: Limit line splitting into 2 parts.

---

pom.xml
src/it/sigOkKeysMapWithPluginDependencies/keysmap.list
src/it/sigOkKeysMapWithPluginDependencies/pom-test.xml
src/it/sigOkKeysMapWithPluginDependencies/postbuild.groovy
src/main/java/org/simplify4u/plugins/ArtifactResolver.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/main/java/org/simplify4u/plugins/keysmap/KeysMap.java
src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeysMapTest.java

This PR produces full transitive resolution of build plug-in dependency libraries, build plug-in dependency-dependencies and dependencies at atypical locations. (See #59)
In addition, the following tweaks are made:
- ~~Failing PGP signature validations are reported as `ERROR` instead of `WARNING`. Reported artifact and detached signature location are part of same message, instead of separate `INFO` lines.~~  
(Partially) obsolete due to more recent changes to reporting behavior.
- ~~Workaround in place for exceptional use cases where POM file is signed but artifact is not, and vice versa.~~ Workaround removed. Resolved with #82.
- ~~In case POM file and artifact are signed with different public keys, users are expected to have both fingerprints contained in the same record of the PGP …

Validate indirect dependencies for build plug-ins, their dependencies

---

src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java

In case you're interested in recording the durations(!?) I found it useful when performing full validation as it can take over 20 seconds even for small projects, so clearly noticeable. Feel free to decline if you're not interested, of course :-)
I use `System.nanoTime()` in the code as this is the only method that guarantees monotonically increasing timestaps such that durations can be measured accurately. (The nanosecond reporting - and possibly precision - is less significant here.)

Report duration of artifact resolution, download and signature validation phases.

---

pom.xml
src/main/java/org/simplify4u/plugins/keyserver/PGPKeyNotFound.java
src/main/java/org/simplify4u/plugins/utils/PublicKeyUtils.java

(Not for release 1.8.0.)
Start showing compiler warnings and fail on these warnings. In my experience any compiler warning is a valid concern to be fixed so why not report them during maven builds and fail on these warnings.

Show, fix and start failing on compiler warnings.

---

src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/main/java/org/simplify4u/plugins/ValidationChecksum.java
src/test/java/org/simplify4u/plugins/ValidationChecksumTest.java

Compare artifacts-list against a checksum created in a prior validation. Effectively, only the first step - compiling the complete artifacts list - needs to be performed in all cases.
A checksum is calculating upon completing a full validation. The checksum is stored in the `target` directory, which contains maven build results. If a validation checksum is present in this directory, the artifacts-list checksum is compared against the stored checksum and if they match, pgpverify exits early with success result, instead of redundantly performing same validation steps.

Checksumming

---

src/main/java/org/simplify4u/plugins/ArtifactResolver.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/main/java/org/simplify4u/plugins/keysmap/KeysMap.java
src/main/java/org/simplify4u/plugins/utils/PGPSignatureUtils.java
src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeysMapTest.java

Misc small improvements.
- Fix javadoc linter warning.
- Consistent coding style.
- Use SLF4J logger and remove constructor injection of Log instance.
- Unnecessary nesting.
Let me know if you want it split up, or you're not interested or whatever. This is just what I gathered while investigating the issue regarding stricter treatment of missing keysmap location.
Also, let me know if you want this squashed too. I did not do it for now, as it makes clearer what sort of changes were made.

Misc small improvements and simplifications

---

src/main/java/org/simplify4u/plugins/ArtifactResolver.java
src/main/java/org/simplify4u/plugins/PGPVerifyMojo.java
src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java

Enable `verifyPlugins` if `verifyPluginDependencies` is enabled.
A unit test tests the four combinations of values for `(verifyPlugins, verifyPluginDependencies)`. I'd like to avoid creating another IT test which is quite heavy on execution time.
TODO: awaiting results from sonar et al.

Implicitly enable verifyPlugins if verifyPluginDependencies is enabled. (Fixes #128)

---

src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java
src/test/java/org/simplify4u/plugins/ValidationChecksumTest.java
src/test/java/org/simplify4u/plugins/keyserver/PGPKeysServerClientTest.java

Addressing sonar issues from https://sonarcloud.io/project/issues?id=org.simplify4u.plugins%3Apgpverify-maven-plugin&resolved=false. #179
However, haven't fully resolved ValidationChecksumTest.java. I don't think "Only one method invocation is expected when testing runtime exceptions" is actually applicable. Since we're testing the builder.
Please can you provide feedback.

Addressing Sonar issues

---

src/main/java/org/simplify4u/plugins/keysmap/KeyInfoItemKey.java
src/test/java/org/simplify4u/plugins/keysmap/KeyInfoTest.java

I gave it a go at fixing #200 . I have replaced `BigInteger` hex string parsing with BC utility class.

Fix zero padded key validation. #200

---

src/main/java/org/simplify4u/plugins/keysmap/KeyInfoItemKey.java
src/test/java/org/simplify4u/plugins/keysmap/KeyInfoTest.java

Make sure error message contains invalid key in case of hex decoding error.

Include invalid key in error message.

---

src/main/java/org/simplify4u/plugins/keyserver/PGPKeysCache.java
src/test/java/org/simplify4u/plugins/keyserver/PGPKeysCacheTest.java

When we have `key not found` status from first server and next server has connection problem we should propagate to client `key not found` instead of last exception.

propagate KeyNotFound on first server to client

---

src/it/noKeyFail/postbuild.groovy
src/main/java/org/simplify4u/plugins/AbstractPGPMojo.java
src/main/java/org/simplify4u/plugins/CheckMojo.java
src/main/java/org/simplify4u/plugins/keyserver/KeyCacheSettings.java
src/main/java/org/simplify4u/plugins/keyserver/PGPKeysCache.java
src/test/java/org/simplify4u/plugins/AbstractPGPMojoTest.java
src/test/java/org/simplify4u/plugins/ShowMojoTest.java
src/test/java/org/simplify4u/plugins/keyserver/PGPKeysCacheTest.java

Store key not found result in cache

---

pom.xml

Our last commit added new functionality, but we failed to bump the minor version.  This is to be consistent with semantic versioning: https://semver.org/

Bump to version 1.16.0-SNAPSHOT since has new functionality

---

pom.xml
src/test/java/org/simplify4u/plugins/AbstractPGPMojoTest.java
src/test/java/org/simplify4u/plugins/ArtifactResolverTest.java
src/test/java/org/simplify4u/plugins/PGPMojoExceptionTest.java
src/test/java/org/simplify4u/plugins/ShowMojoTest.java
src/test/java/org/simplify4u/plugins/ValidationChecksumTest.java
src/test/java/org/simplify4u/plugins/keyserver/KeyServerClientSettingsTest.java
src/test/java/org/simplify4u/plugins/keyserver/PGPKeysCacheTest.java
src/test/java/org/simplify4u/plugins/keyserver/PGPKeysServerClientTest.java
src/test/java/org/simplify4u/plugins/keyserver/RoundRobinRouterPlanerTest.java
src/test/java/org/simplify4u/plugins/keysmap/ArtifactPatternTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemAnyKeyTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemBrokenSigTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemFingerprintTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemNoKeyTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemNoSigTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeyItemsTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeysMapMultiTest.java
src/test/java/org/simplify4u/plugins/keysmap/KeysMapTest.java
src/test/java/org/simplify4u/plugins/pgp/PublicKeyUtilsTest.java
src/test/java/org/simplify4u/plugins/pgp/ReportsUtilsTest.java
src/test/java/org/simplify4u/plugins/pgp/SignatureUtilsTest.java
src/test/java/org/simplify4u/plugins/skipfilters/CompositeSkipperTest.java
src/test/java/org/simplify4u/plugins/skipfilters/ProvidedDependencySkipperTest.java
src/test/java/org/simplify4u/plugins/skipfilters/ScopeSkipperTest.java
src/test/java/org/simplify4u/plugins/skipfilters/SnapshotDependencySkipperTest.java
src/test/java/org/simplify4u/plugins/skipfilters/SystemDependencySkipperTest.java
src/test/java/org/simplify4u/plugins/utils/ExceptionUtilsTest.java
src/test/java/org/simplify4u/plugins/utils/MavenCompilerUtilsTest.java

migrate to JUnit from TestNG

---

src/main/java/org/simplify4u/plugins/AbstractPGPMojo.java
src/main/java/org/simplify4u/plugins/CheckMojo.java

Also - not the typo, but I took the liberty to synchronize _key**s** servers_ to _key servers_ in once place, as used in other sections.

Fix some typos in docs

---

src/it/multipleKeysMap-duplicates-fail/invoker.properties
src/it/multipleKeysMap-duplicates-fail/keysmap1.list
src/it/multipleKeysMap-duplicates-fail/keysmap2.list
src/it/multipleKeysMap-duplicates-fail/pom-test.xml
src/it/multipleKeysMap-duplicates-fail/postbuild.groovy
src/it/multipleKeysMap-duplicates-log/keysmap1.list
src/it/multipleKeysMap-duplicates-log/keysmap2.list
src/it/multipleKeysMap-duplicates-log/pom-test.xml
src/it/multipleKeysMap-duplicates-log/postbuild.groovy
src/it/multipleKeysMap-no-duplicates/keysmap1.list
src/it/multipleKeysMap-no-duplicates/keysmap2.list
src/it/multipleKeysMap-no-duplicates/pom-test.xml
src/it/multipleKeysMap-no-duplicates/postbuild.groovy
src/main/java/org/simplify4u/plugins/CheckMojo.java
src/main/java/org/simplify4u/plugins/DuplicateKeyMapKeyItemException.java
src/main/java/org/simplify4u/plugins/keysmap/KeyItems.java
src/main/java/org/simplify4u/plugins/keysmap/KeysMap.java

Flag to fail on keymap duplicate key item
